sudo: required
language: python
python: 2.7

env:
  global:
  - MULLED_NAMESPACE=biocontainers
  - secure: LASKXjmFlLUipYLlg0CcK3AbXxq4YYve+k3c7lXB2z6ixpn2/2juq0c4faEiFwM0Opt2GyAp91S8l3/Fbu2r4yKTagv9H3id/nB5iFNmLDYf3Hv0zStrmw2T/sUw4AbgDnkpzCJ6ey/rrF81turxDRbRdMprbYryL3I+8CsWU1YzH1LIv0No8CuB/jQh2tFz456Rmwb84WK5rC/zP8Bvd7z5lvnHuc/qKLiMLjmMepIjx+yF61N3d7p7SQR/5OvW7OHUfBd5QEybMdoe5XnMi+1VvmFl4P7GIqivOTiNiqb+sZv/SXFRKeaM1QoRTYjuYyJQI/bTBIWvAmoVqMpy5pFGzAAoD4GhfPJfDcVTxRhO6B0t0b3PccfXnc+ZgHF+WO7bjI/ub0k+G2ed7g3B9nc09QdSkyKyoYrV8ce/T1UpRPyVd6OhhxmrPcHGG87FvxMikAlnHWXFBWHgwL1TFY5O92uWqY1EaIVHVd8tkXOBqPNa/2/D90jIMgsuw7IKiTSuEtPwfIWCjyh9Rs34U6kOvXZcT3xfseB8XdYz08Ogt4oTMt028hsJA96H8LKx/ezxDO5ZI96Ge0j/y0W6CvnatEwxFtkaBBwpw0vtVaMh6Aimey5wqMCn698gdzToINHOJq87xOccG3JSOTnO+MhxWQQlh6aTQP2jjSFkH2s=
  - secure: hfMqkWrskhAxvXsbLB0oL+oziY1S7nVDgLhR0YkvsEwXlNNOLinErw9KuQkSNjXpM7zkICWiwS9Q5eigKkIbNxbXo3vjdLh5CNqIUT05ynR3AhpCA8TbE7v0Jpq2fT44T5vb5/aP2g8aUmMslGFtvgbAEf8bhPImV03XBP6sF1u5g3gGwetDJ+pQufV79E60JiLYpGSq8rmmcChQfmdZkA/IxTtRkv97qfpTr6JpNyrCxhPMd3jXjrA8uTGsY0v6/SnhkGd5PKsjgOim874G63MlBg8WFXOxlsD3YkkJKsYbcwHC14m3sXU5ewvyyVD/wI1N1JrNqG2/YnL2cA+sCn5/LQ0GNGQJze2kMSGwmCbbPR1SPJxbplh0VhMoBMXcaWrCNaInye81GU+KWdWwA2SRQ70RgsWCh+wWvYF+B7s0jFcTT6gDWVh8XG5W31f1VcRer+zxhe4Kzvyr8zhx3uWhfQeJJ4656gnFQ99nHoGZbRfLB5Rro/PSrm4dVcTHwsKjBWO2xqnUACEzTA96/6UVfGQ3oQeWiyzcVEsht7v0U1FETW3ze8WdFzb16pdkJGeel2O7zmBwjjStST88akVJH9zmMTz6XXVZXeh2M79mo/82ppUDoUKKAZMhTawOCetFfr1XLMB4WiTVK0i0SiXLlPigh5eo3QnnBULNxIo=
  - secure: YjpgNHxOzbLnDhWsH1IFelX21yjhSyUcl1KVw/5/0DwFn3HRW88iwe8rUSfYlENNKwrdXJSXEzXs52uqMUq1WMkSQxCMOew9V3HzSu+r6NJHR4ucok5V2O1KlIicHUQ/ckzd3gehS32fKTno2aIdC/aH5i1S8e1uf3YfNG/BA2RmsiSahm9p9qi0l8GgrBJYfPVLsDt5nIAQsRNJFjg/wI7r6D3tyA5BIcwRvWrmBJBofIdlsTB7kEOGOVCTvRrKsvCpWnD5UZ998wMb2yABKFjBrQ4253vBwdPARSQf0qRieF2UkFXPfBEQ5f9eBL8b0dBlHV71E3nYxA8rIc+LmJszNjxjcGuuheIVc78oNVR/x9pY6s89cxqBNwkhbdv3xNyfdMo//LMe016l8UNZb7LWy3mrnNZKZ8BZ+cUm5GRQfS9PLv1BVVvGkTYZEwTokzFthd5g/WevZN2aLozzf28hxVUaAj8tS+K05XUYFnzJJ3wDDV68Aj/MB52Ol12YifXPdv3r2yM83pzyLLBFW4t9eK52Kbj9Zf4+wf2cLwO7DbIvDSr1NKthmJ9TusfL/5hA/Bjp35vIJ2dTI1sJti2nk2s1Zvu1aw0Jq0ffB5bjJ3gfetj618POdUvB9lq+YSZUTeYCwC6NSj/c5IaYOFI5h010tRmniH/CPWr5p+8=

services:
- docker

before_install:
- set -e
- rm -rf /home/travis/perl5/ /home/travis/.phpenv /home/travis/gopath /home/travis/otp
  /home/travis/.gimme/ /home/travis/.rvm /home/travis/.nvm
- pip install requests
##- pip install git+https://github.com/galaxyproject/galaxy-lib@channel_cleanup
- pip install galaxy-lib
##- pip install https://github.com/galaxyproject/galaxy-lib/archive/tripple.zip
- wget http://mirrors.kernel.org/ubuntu/pool/universe/s/sshpass/sshpass_1.06-1_amd64.deb
- sudo apt-get update -qq
- sudo apt-get install docker-ce --no-install-recommends -y -o Dpkg::Options::="--force-confmiss"
  -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew"
- sudo dpkg -i sshpass_1.06-1_amd64.deb
- docker --version
- docker info

script:
- set -e
- mulled-build-files --check-published --singularity --namespace $MULLED_NAMESPACE
  build-and-test ./combinations --verbose
- ls -la ./singularity_import

after_success:
- |
  if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then

    openssl aes-256-cbc -K $encrypted_69030c032500_key -iv $encrypted_69030c032500_iv -in galaxy_depot_travis.enc -out ~/.ssh/galaxy_depot_travis -d 
    chmod 600 ~/.ssh/galaxy_depot_travis
    printf "%s\n" \
        "Host orval.galaxyproject.org" \
        "  IdentityFile ~/.ssh/galaxy_depot_travis" \
        "  LogLevel ERROR" >> ~/.ssh/config
    eval $(ssh-agent)
    sshpass -e -P 'Enter passphrase for' ssh-add ~/.ssh/galaxy_depot_travis

     mulled-build-files --check-published --namespace $MULLED_NAMESPACE --oauth-token $QUAY_OAUTH_TOKEN push ./combinations;
     ls -la singularity_import;
     ssh-keyscan -t rsa orval.galaxyproject.org >> ~/.ssh/known_hosts;
     [ "$(ls -A singularity_import)" ] && echo 'uploading Singularity images' && scp singularity_import/mull* singularity@orval.galaxyproject.org:/srv/nginx/depot.galaxyproject.org/root/singularity/
  fi
